import type { Metadata } from "next";
import Link from 'next/link'; 
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Tournamax Assignment",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="max-w-3xl mx-auto text-slate-800">
          <header className="p-6 border-b flex  item-centre  justify-between bg-yellow-500 rounded-bl-lg rounded-br-lg">
            <Link className="text-2xl font-bold text-white" href={"/"}>Tournamax Assignment</Link>
            <Link className="bg-slate-100 grid place-item-centre py-2 px-4 rounded-full font-bold" href={'/create'}>Add Topic</Link>
          </header>
          <main className="p-4 text-lg">{children}</main>
        </div>
      </body>
    </html>
  );
}
